### ISSUE TITLE
没必要吧编译中间产物放进压缩包

### ISSUE THREAD

**Issue by Andy5972** [musiclover789/luna#2]
没必要吧编译中间产物放进压缩包

**Comment by shaojava** [comment]
![image](https://github.com/musiclover789/luna/assets/4945550/ae7066a4-1638-4ef9-ae35-f341f7e87df1)
精简后文件目录

**Comment by Andy5972** [comment]
删掉无用的文件 luna-temp 的UA 仍然可以使用  其他未授权的功能不知道是啥 用不到

**Comment by Andy5972** [comment]
![image](https://github.com/musiclover789/luna/assets/4945550/e21c5648-f8a7-4f2c-812d-2e2e54c18173)
500M不到

**Comment by Andy5972** [comment]
0b0744bu500v0f960r2f0n0s7jbs5k4753c90e3j56ck453w66700oa44w495o82504s1t737mf9565452c6049j5vca4r551b7h27et05b111er5e925v4b15720o1r097655an078v0d1w0e652j660z4q16b65y920z3u17ax674p5ue31599009009221s7c7gc3502a0z8v50915d7o4bd5158864305dd3452d5yce501744870j5t0e4z0567084n586c5o107m96002k5kan5aba548w16ap6t620r554d7c12af007x4c677kd80p020oa80e2x53a21f5x4p356cf55ea442465hbq5kda1a050o84541757bs0x0a037j05bo27dk593e024e5id05u621q96635f0wag11cn5u8b5c58433l7q0u5q0759870893008b109k46c2623151di4d3d06d95v491546

授权文件内容 给个授权版 看看功能
